services:
  db:
    image: postgres:17.6-alpine
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    
